set_output:
  description: "Set the value of an output on the controller e.g. setting the lights to AUTO (Automatic) instead of using the switch entity in HA which only supports OFF/ON"
  fields:
    did:
      name: DID
      description: "DID of selected output, can be obtained from attributes of the given switch in HA"
      example: "3_1"
      selector:
        text:
    setting:
      name: Setting
      description: "Setting to set the output to e.g. ON/OFF/AUTO"
      selector:
        select:
          options:
            - "OFF"
            - "ON"
            - "AUTO"
set_variable:
  description: "Ability to program variables on the controller with either a value or code. Either 'Code' or 'Value' must be specified. 'Code' will override any 'Value' if it is specified. This service will set 'Advanced' mode on the requested variable, and the variable will need to be switched to 'AUTO' using the 'apex.set_output' service call."
  fields:
    did:
      name: DID
      description: "DID of the selected variable or output to modify"
      example: "Cntl_A1"
      selector:
        text:
    value:
      name: Value
      description: "(OPTIONAL) Value to set on the variable. This will create a program of the form 'Set (value)'"
      example: "75"
      selector:
        text:
    code:
      name: Code
      description: "(OPTIONAL) Code to modify on the variable/output. If Code is not specified, "
      example: "Set 75"
      selector:
        text:
