set_output:
  description: "Set the value of an output on the controller e.g. setting the lights to AUTO (Automatic) instead of using the switch entity in HA which only supports OFF/ON"
  fields:
    did:
      name: DID
      description: "DID of selected output, can be obtained from attributes of the given switch in HA"
      example: "3_1"
      selector:
        text:
    setting:
      name: Setting
      description: "Setting to set the output to e.g. ON/OFF/AUTO"
      selector:
        select:
          options:
            - "OFF"
            - "ON"
            - "AUTO"
set_variable:
  description: "Set the program for variables on the controller. This service will set the Apex output to 'Advanced' control type. To recognize the change, the output must be set to 'AUTO' using the 'apex.setoutput' service."
  fields:
    did:
      name: DID
      description: "DID of the selected variable output to modify"
      example: "Cntl_A1"
      selector: 
        text:
    code:
      name: Code
      description: "Code for on the variable output"
      example: "Set 75"
      selector:
        text:
